# Generated by Django 5.2.7 on 2025-11-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='library',
            name='location',
        ),
    ]
